spring:
    data:
        mongodb:
            database: usersdb
            uri: mongodb+srv://pablovpmadrid:Marx1230@cluster0.q8xteea.mongodb.net/?retryWrites=true&w=majority
            auto-index-creation: true
springdoc:
    swagger-ui:
        path: /swagger-ui.html

logging:
    level:
        org:
            springframework: DEBUG
